version: "2"
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      - skynet

  skydive-analyzer:
    image: skydive/skydive
    ports:
      - "8082:8082"
      - "8082:8082/udp"
    links:
      - elasticsearch
    command: analyzer --listen=0.0.0.0:8082
    environment:
      - SKYDIVE_STORAGE_ELASTICSEARCH_HOST=elasticsearch:9200
      - SKYDIVE_ANALYZER_STORAGE_BACKEND=elasticsearch
      - SKYDIVE_GRAPH_BACKEND=elasticsearch
      - SKYDIVE_ETCD_LISTEN=0.0.0.0:12379
    networks:
      - skynet

  skydive-agent:
    image: skydive/skydive
    depends_on:
      - skydive-analyzer
    ports:
      - "8081:8081"
    network_mode: "host"
    pid: "host"
    command: agent --listen=0.0.0.0:8081
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/netns:/host/run
      - /var/run/openvswitch/db.sock:/var/run/openvswitch/db.sock
    environment:
      - SKYDIVE_AGENT_TOPOLOGY_NETNS_RUN_PATH=/host/run
      - SKYDIVE_ANALYZERS=127.0.0.1:8082

networks:
  skynet:
