---
# tasks file for ensure-docker
- name: Load required facts
  setup:
    gather_subset: min,network

# https://github.com/docker/compose/issues/6463
- name: Bump sshd MaxSessions to avoid remoting errors
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MaxSessions "
    line: "MaxSessions 501"
  notify: restart-sshd

- name: Install docker dependencies
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Perform docker ipv6 tricks
  when: docker_ipv6
  include_tasks: ipv6.yml

- name: Run ensure-docker role from zuul-jobs
  vars:
    # bug in role, fails without it
    ansible_user: root
  include_role:
    name: ensure-docker # from zuul-jobs
