---
# see https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file

# from galaxy
# - src: avinetworks.docker

# - src: https://opendev.org/zuul/zuul-jobs.git
roles:
  - src: https://github.com/DataDog/ansible-datadog.git
  - src: geerlingguy.nfs
  - src: geerlingguy.samba
collections:
  - name: ansible.posix
    # type: git
    # version: devel
  - name: community.aws
  - name: community.docker
  - name: community.general  # ipmi_boot
