---
- name: load ansible_pkg_mgr
  setup:
    filter: "*"
  when: ansible_pkg_mgr is not defined

- name: determine if we are to use proxy or not
  set_fact:
    use_proxy: "{{ http_proxy is defined or https_proxy is defined }}"

- name: configure system proxy variables
  when: use_proxy
  become: true
  copy:
    dest: /etc/profile.d/proxy.sh
    content: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ http_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ http_proxy }}
      ftp_proxy={{ http_proxy }}
      export http_proxy https_proxy ftp_proxy HTTP_PROXY HTTPS_PROXY

- name: create proxy env file
  when: not use_proxy
  become: true
  file:
    path: /etc/profile.d/proxy.sh
    state: absent

- name: configure wget proxy
  become: true
  copy:
    dest: /etc/wgetrc
    content: |
      {% if http_proxy is defined or https_proxy is defined %}
      http_proxy = {{ http_proxy_no_schema }}
      https_proxy = {{ http_proxy_no_schema }}
      ftp_proxy = {{ http_proxy_no_schema }}
      {% endif %}

- name: "configure packager proxy: {{ pkg_mgr_map[ansible_pkg_mgr] }}"
  become: true
  when: pkg_mgr_map[ansible_pkg_mgr] | default(false)
  ini_file:
    path: "{{ pkg_mgr_map[ansible_pkg_mgr] }}"
    section: main
    option: proxy
    value: "{{ http_proxy | default(omit) }}"
    state: "{% if http_proxy is defined or https_proxy is defined %}present{% else %}absent{% endif %}"

- name: install custom CA
  when: custom_ca is defined
  become: true
  copy:
    dest: /etc/pki/ca-trust/source/anchors/custom-ca.crt
    content: "{{ custom_ca }}"
  register: result

- name: activate custom CA
  when: result is changed
  become: true
  command: update-ca-trust

- name: configure pip to use system ca certificates
  when: custom_ca is defined
  become: true
  ini_file:
    path: /etc/pip.conf
    section: global
    option: cert
    value: /etc/ssl/certs/ca-bundle.crt
