#!/usr/bin/env bash
set -euxo pipefail
# avoid retarded errors: proxy: unknown scheme: http
unset http_proxy
unset https_proxy
unset ALL_PROXY
unset ftp_proxy

docker run -d --name=netdata \
    -p 19999:19999 \
    -v /proc:/host/proc:ro \
    -v /sys:/host/sys:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --cap-add SYS_PTRACE \
    --security-opt apparmor=unconfined \
    netdata/netdata
