#!/usr/bin/env ansible-playbook -vv
---
- hosts: localhost
  become: false
  vars:
    app:
      name: unifi
  tasks:
    - name: install reqs
      pip:
        name: docker-compose

    - block:
        - name: compose down
          community.docker.docker_compose:
            project_name: "{{ app.name }}"
            project_src: "{{ playbook_dir }}"
            state: absent
          register: result

        # dompose-up may fail with name conflict if container with same name
        # already exists, even if is not running, so we need to enforce its removal.
        - name: Remove container
          community.docker.docker_container:
            name: "{{ app.name }}"
            state: absent

        - name: compose up
          community.docker.docker_compose:
            build: true
            debug: true
            pull: true
            recreate: always
            restarted: true
            project_name: "{{ app.name }}"
            remove_orphans: true
            project_src: "{{ playbook_dir }}"
          register: result

        # - name: get info about container
        #   docker_container_info:
        #     name: "{{ app.name }}"
        #   register: result2
        #   failed_when: not result.container.State.Running
        #   retries: 3
        #   delay: 5

      rescue:
        - name: print debug info
          debug:
            var: result

        # - name: display docker logs
        #   shell: |
        #     docker logs {{ app.name }}
        #   register: result

        - name: compose down
          community.docker.docker_compose:
            project_name: "{{ app.name }}"
            project_src: "{{ playbook_dir }}"
            state: absent

        # - name: assure we fail the playbook
        #   fail:
        #     msg: |
        #       "{{ result.module_stderr | join('\\n') }}"
        #       "{{ result.module_stdout | join('\\n') }}"

        - debug:
            msg: Controller web interface shoul be visible at http://unifi.sbarnea.com:18080
