---
- name: check if pip is present
  command: command -v pip
  failed_when: false
  register: command_pip
  changed_when: false

- name: install pip
  when: command_pip.rc != 0
  become: true
  block:
    - name: download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /root/get-pip.py

    - name: install pip
      command: python /root/get-pip.py
      args:
        warn: false

- name: install pip packages
  become: true
  pip:
    name:
      - docker
      - docker-compose
    state: present
    # extra_args: --user
# - name: additional pythons for tox
#   package:
#     name:
#       - centos-release-scl

# - name:
#   package:
#     - rh-python34-python-devel
#     - rh-python35
#     - rh-python35-python-devel
#     - rh-python35-psycopg2
#     - rh-python35-sqlalchemy
#     - rh-python36
#     - rh-python36-psycopg2
#     - rh-python36-sqlalchemy
#     - rh-python36-python-devel
#     - gcc
#     - patch
#     - sqlite-devel
#     - readline-devel
#     - openssl-devel
#     - python-devel
#     - sclo-python35-python-tox
