---
# Based on a true story from
# https://blog.bobbyallen.me/2013/02/03/how-to-redirect-local-root-mail-to-an-external-email-address-on-linux/
- name: forward root email
  become: true
  lineinfile:
    dest: /etc/aliases
    regexp: "^(.*)root:(.*)"
    line: "root:  {{ sysadmin_email }}"
  register: result

- when: result is changed
  block:
    - name: gather ansible_hostname
      setup:
        gather_subset:
          - "!all"

    - name: install mail related packages
      become: true
      package:
        name:
          - postfix
          - mailx
        state: present

    - name: call newaliases
      become: true
      command: /usr/bin/newaliases

    - name: restart postfix
      become: true
      service:
        name: postfix
        state: restarted
        enabled: true

    - name: sent test email
      become: true
      shell: |
        echo 'ansible configured email on {{ ansible_hostname }}' | mail -s '{{ ansible_hostname }}: ansible test' root
