---
# based on https://pulpproject.org/2020/03/15/pulp-fedora31-single-container/
version: "3.7"
services:
  pulp:
    image: pulp/pulp-fedora31
    container_name: pulp
    network_mode: bridge
    ports:
      - 24816:24816
    volumes:
      - /opt/data/pulp/settings:/etc/pulp
      - /opt/data/pulp/storage:/var/lib/pulp
      - /opt/data/pulp/db:/var/lib/pgsql
      - /opt/data/pulp/containers:/var/lib/containers
    labels:
      - traefik.enable=true
      - traefik.http.routers.pulp.rule=Host(`pulp.sbarnea.com`)
      - traefik.http.routers.pulp.tls.certResolver=myresolver
      - traefik.http.routers.pulp.entrypoints=websecure
      - traefik.http.services.pulp.loadbalancer.server.port=24816
