---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: collections.yml
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
