# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "r7"
  config.vm.box = "generic/rhel7"
  config.vm.network "private_network", type: "dhcp"

  config.vm.network "forwarded_port", guest: 22, host: 2222

  config.ssh.password = "redhat"
  config.ssh.username = "root"
  config.ssh.remote_user = "root"

  # needed:
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # config.vm.network "public_network", adapter: 1, bridge: "en0: Ethernet"

  # auto_config: false, bridge: [
  #   "en0",
  #   "en0: Ethernet",
  #   "en1: Wi-Fi (AirPort)"
  # ], adapter: 0

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.name = "r7"
  #   vb.gui = true
  
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  # #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
