---
- name: remove outdated OS packages
  # https://github.com/ansible/ansible/issues/50843
  # package:
  #   name:
  #     - /usr/bin/tox
  #   state: absent
  shell: |
    sudo {{ ansible_pkg_mgr }} remove -y  /usr/bin/tox
  args:
    warn: false
  register: result
  failed_when: result.rc != 0 and 'No packages marked for removal' not in result.stderr
  changed_when: |
    'No packages marked for removal' not in result.stderr

- debug: var=result

- name: install sys deps
  package:
    name:
      # - the_silver_searcher  # missing from centos8
      - rsync
      - python36 # centos8
      - make
  become: true

- name: install seashells for easy sharing console
  pip:
    name:
      - seashells
      - tox
    extra_args: --user

- name: create sea utility function
  copy:
    content: |
      sea () {
        $* 2>&1 | seashells
      }
    dest: /etc/profile.d/seashells.sh
  become: true
