---
- name: update system
  package:
    name: "*"
    state: latest
  become: true

- name: install virsh packages
  package:
    name:
      # - bridge-utils  # missingin c8
      - ebtables
      - libguestfs-tools
      - libvirt
      - libvirt-client
      - qemu-kvm
      - virt-install
      - virt-top
    state: present
  become: true

- name: enable libvirtd
  service:
    name: libvirtd
    enabled: true
    state: started

- name: validate virsh
  command: |
    virsh list
  changed_when: false
