---
- name: gather facts
  setup:
    filter: "*"
  when: ansible_pkg_mgr is not defined

- name: configure freebsd repository
  copy:
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    content: |
      FreeBSD: {
        url: "pkg+https://pkg.freebsd.org/freebsd:11:x86:64/latest",
        mirror_type: "srv",
        # signature_type: "fingerprints",
        # fingerprints: "/usr/local/share/pfSense/keys/pkg",
        enabled: yes
      }

- name: install freebsd packages
  pkgng:
    name:
      - atop
      - htop
      - iftop
      - mc
      - ncdu
      - nmap
      - ntopng
      - oath-toolkit
    pkgsite: FreeBSD
  register: result

- name: rehash
  when: result is changed
  # rehash is shell build-in on opnsense
  shell: rehash || true
  args:
    warn: false

- debug: var=result

- name: deploy ovpn-get-auth
  copy:
    dest: /root/ovpn-get-auth
    mode: u+x
    content: |
      #!/usr/bin/env sh
      while true; do
        printf "{{ vpn_username }}\n{{ vpn_otp_pin }}`oathtool --totp -b {{ vpn_otp_seed }}`" > ~/.cache/ovpn-pipe
      done

- name: deploy ovpn-pipe
  copy:
    dest: /usr/local/etc/rc.d/ovpn-pipe.sh
    mode: u+x
    content: |
      #!/usr/bin/env sh
      set -eu
      pkill -f ovpn-get-auth || true
      mkdir -p ~/.cache
      rm -rf ~/.cache/ovpn-pipe
      mkfifo -m 0600 ~/.cache/ovpn-pipe || true
      nohup sh /root/ovpn-get-auth >>/var/log/ovpn-pipe.log 2>&1 </dev/null &

- name: start ovpn-pipe
  command:
    cmd: sh /usr/local/etc/rc.d/ovpn-pipe.sh
    warn: false
  changed_when: false
