---
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: sbarnea.com
            sans:
              - "*.sbarnea.com"

certificatesResolvers:
  myresolver:
    acme:
      email: sorin.sbarnea@gmail.com
      storage: /data/acme.json
      # tlsChallenge: {}
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # entryPoint: https
      # tlsChallenge:
      #   entryPoint: https
      # httpChallenge:
      #   entryPoint: http
      dnsChallenge:
        provider: route53
        delayBeforeCheck: 10

log:
  filePath: /data/traefik.log
  # level: DEBUG
  format: common
accessLog:
  filePath: /data/access.log
  filters:
    statusCodes:
      - 100-199
      - 400-499
      - 500-599
  # level: DEBUG

# Enable API and dashboard
api:
  insecure: true
  dashboard: true

ping:
  {}
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

providers:
  docker:
    # Docker server endpoint. Can be a tcp or a unix socket endpoint.
    #
    # Required
    # Default: "unix:///var/run/docker.sock"
    #
    # endpoint = "tcp://10.10.10.10:2375"

    # Default host rule.
    #
    # Optional
    # Default: "Host(`{{ normalize .Name }}`)"
    #
    # defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"
    exposedByDefault: true
  file:
    filename: /data/traefik-dynamic.yml
    watch: true

serversTransport:
  # needed for unifi controller
  # https://community.ui.com/questions/Does-anyone-run-UniFi-with-Traefik-reverse-proxy/d41da74d-d82a-4d68-aa4c-64606de45307
  insecureSkipVerify: true
