#!/usr/bin/env bash
# see https://github.com/pducharme/UniFi-Video-Controller

set -euxo pipefail
unset http_proxy
docker pull pducharme/unifi-video-controller
docker stop nvr || true
docker rm nvr || true
docker create \
  --name=nvr \
  --hostname nvr.sbarnea.com \
  -v /opt/data/nvr/config:/var/lib/unifi-video \
  -v /mnt/media/nvr:/var/lib/unifi-video/videos \
  -e PUID=99 \
  -e PGID=100 \
  -e DEBUG=1 \
  --cap-add SYS_ADMIN \
  --cap-add DAC_READ_SEARCH \
  -p 10001:10002 \
  -p 1935:1935 \
  -p 6666:6666 \
  -p 7080:7080 \
  -p 7442:7442 \
  -p 7443:7443 \
  -p 7444:7444 \
  -p 7445:7445 \
  -p 7446:7446 \
  -p 7447:7447 \
  --restart unless-stopped \
  pducharme/unifi-video-controller:latest

#   --network bridge \
#   --ip 192.168.33.50 \
docker start nvr
