---
ansible_network_os: dsm

python_cmd: python
pxe_root: /volume2/PXE

# workaround for Synology DSM issue:
# [WARNING]: sftp transfer mechanism failed on [...]. Use ANSIBLE_DEBUG=1 to see detailed information
ansible_ssh_transfer_method: scp

docker_volumes_root: /volume1/docker/

# first one is used for wol wake
mac_addresses:
  - 00:11:32:45:ca:9d

wol:
  mac: 00:11:32:45:ca:9d
  port: 9
  # 5000
  address: 255.255.255.255
