#!/usr/bin/env ansible-playbook
---
- name: configure specific pxe boot menus
  hosts: baremetals
  # at least some are offline
  gather_facts: false
  vars:
    boot_options:
      centos7:
        name: centos
        version: 7
        template: redhat
        ks_os_repo: "{{ distros_mirror }}/centos/7/os/x86_64/"
      centos8:
        name: centos
        version: 8
        template: redhat
        ks_os_repo: "{{ distros_mirror }}/centos/8/BaseOS/x86_64/os/"
      fedora28:
        name: fedora
        version: 28
        template: redhat
        ks_os_repo: "{{ distros_mirror }}/fedora/linux/releases/28/Server/x86_64/os/"
      rhel8:
        name: rhel
        version: 8
        template: redhat
        ks_os_repo: "{{ distros_mirror }}/rhel/8/os/x86_64/"
  tasks:

    - name: configure ks facts
      set_fact:
        ks_host_id: "{{ mac_addresses[0] | regex_replace(':', '-') | lower }}"
        ks_os_name: "{{ boot_options[os_flavour].name }}"
        ks_os_version: "{{ boot_options[os_flavour].version }}"
        ks_os_repo: "{{ boot_options[os_flavour].ks_os_repo }}"
        ks_template: "{{ boot_options[os_flavour].template }}"
        ks_hostname: "{{ inventory_hostname }}"
        ks_bond_mac: "{{ mac_addresses[0] | regex_replace('-', ':') | upper }}"
        ks_services:
          - lldpd
          - ntpd
          - sshd
        ks_packages:
          - ca-certificates
          - curl
          - deltarpm
          - net-tools
          - ntp
          - vim-enhanced
        ks_repo_updates: ''

    - name: set ks snmpp vars
      when: snmp is defined and snmp
      set_fact:
        ks_services: "{{ ks_services }} + [ 'snmpd' ]"
        ks_packages: "{{ ks_packages }} + [ 'net-snmp' ]"

    - name: set ks vars
      when: ks_os_name != 'fedora'
      set_fact:
        ks_services: "{{ ks_services }} + [ 'network' ]"
        ks_packages: "{{ ks_packages }} + [ 'screen' ]"

    - name: set centos specific facts
      when: ks_os_name == 'centos'
      set_fact:
        ks_packages: "{{ ks_packages }} + [ '@base', '@hardware-monitoring', '@system-admin-tools' ]"
        ks_repo_updates: |
            repo --name=updates --baseurl={{ distros_mirror }}/{{ ks_os_name }}/{{ ks_os_version }}/updates/x86_64

    - name: set fedora specific facts
      set_fact:
        ks_repo_updates: |
            repo --name=updates --baseurl={{ distros_mirror }}/fedora/linux/updates/{{ ks_os_version }}/Everything/x86_64/
      when: ks_os_name == "fedora"

- hosts: hero
  gather_facts: false
  tasks:
    # - include_role:
    #     name: dsm-entware
    - include_role:
        name: pxe
